#!/bin/sh
source /var/lib/dboxed/netbird/netbird.env

ARGS=
if [ "$NETBIRD_MANAGEMENT_URL" != "" ]; then
  ARGS="$ARGS --management-url=$NETBIRD_MANAGEMENT_URL"
fi
if [ "$NETBIRD_HOSTNAME" != "" ]; then
  ARGS="$ARGS --hostname=$NETBIRD_HOSTNAME"
fi

exec netbird service run \
  --log-file=console \
  $ARGS \
  2>&1
