#!/bin/sh
if [ -f /var/lib/dboxed/sandbox.env ]; then
  source /var/lib/dboxed/sandbox.env
fi
exec dboxed volume-mount \
  --work-dir={{ .DboxedWorkdir }} \
  serve {{ .VolumeId }} \
  --backup-interval={{ .BackupInterval }} \
  2>&1
