
version: 2
pro: true

builds:
  - id: dboxed
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/dboxed
    binary: dboxed
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-apple-darwin21.1-clang{{- end }}
        {{- end }}
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "amd64"}}CC=x86_64-linux-gnu-gcc{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-linux-gnu-gcc{{- end }}
        {{- end }}
    ldflags:
      - -s -w
      - '{{ if ne .Env.NO_GO_VERSION "1" }}-X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X main.builtBy=goreleaser{{ end }}'

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

dockers_v2:
  - id: linux
    images:
      - ghcr.io/dboxed/dboxed
    tags:
      - "v{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.description": "Dboxed"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
  - id: infra-image-sandbox
    images:
      - ghcr.io/dboxed/dboxed-infra-sandbox
    tags:
      - "v{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.description": "Dboxed infra-sandbox-image"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    dockerfile: infra-images/sandbox/Dockerfile
    extra_files:
      - infra-images/sandbox
  - id: infra-image-volume
    images:
      - ghcr.io/dboxed/dboxed-infra-volume
    tags:
      - "v{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.description": "Dboxed infra-volume-image"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    dockerfile: infra-images/volume/Dockerfile
    extra_files:
      - infra-images/volume
  - id: infra-image-caddy
    images:
      - ghcr.io/dboxed/dboxed-infra-lb-caddy
    tags:
      - "v{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    build_args:
      CADDY_VERSION: "2.10"
    labels:
      "org.opencontainers.image.description": "Dboxed caddy"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    dockerfile: infra-images/caddy/Dockerfile
    extra_files:
      - infra-images/caddy

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nightly:
  publish_release: true
  keep_single_release: true

release:
  github:
    owner: dboxed
    name: dboxed
  make_latest: "{{ not .IsNightly }}"
  extra_files:
    - glob: hack/install.sh
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
