FROM golang:1.24.3

# See https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope
ARG TARGETARCH
ENV ARCH=$TARGETARCH

ARG VERSION

ADD . .

ENV GOCACHE=/root/.cache/go-build

RUN --mount=type=cache,target=/go/pkg/mod/ \
    --mount=type=cache,target="/root/.cache/go-build" \
    CGO_ENABLED=1 go build -ldflags="-extldflags=-static -X 'main.Version=$VERSION'" -o /unboxed ./cmd/unboxed
