#!/usr/bin/env bash

PROG=$1
OS=$2
ARCH=$3
shift 3

case ${OS} in
  linux)
    ZIG_OS=linux
    ;;
  darwin)
    ZIG_OS=macos
    SYSROOT="$(xcrun --show-sdk-path)"
    EXTRA_ARGS="--sysroot $SYSROOT -I/usr/include -L/usr/lib -F$SYSROOT/System/Library/Frameworks -Wno-nullability-completeness"
    ;;
  *)
    fatal "Unsupported os ${OS}"
esac

case ${ARCH} in
  arm64|aarch64|armv8l)
    ZIG_ARCH=aarch64
    ;;
  amd64|x86_64)
    ZIG_ARCH=x86_64
    ;;
  *)
    fatal "Unsupported architecture ${ARCH}"
esac

zig $PROG -target ${ZIG_ARCH}-${ZIG_OS} $EXTRA_ARGS "$@"
