#cloud-config
runcmd:
  - |
    echo "enabling swap"
    MEM=$(cat /proc/meminfo | grep '^MemTotal: ' | awk '{print $2}')
    MEM=$(($MEM * 1024))
    SWAP=$(($MEM * 2))
    fallocate -l $SWAP /swap.bin
    chmod 0600 /swap.bin
    mkswap /swap.bin
    echo "/swap.bin swap swap defaults 0 0" >> /etc/fstab
    swapon -a
  - |
    export VERSION_DBOXED="{{ .DboxedVersion }}"
    curl -fsSL https://dboxed.io/install.sh | bash
  - |
    export DBOXED_API_URL="{{ .ApiUrl }}"
    export DBOXED_API_TOKEN="{{ .ApiToken }}"
    dboxed machine service install "{{ .MachineId }}"
